project:
  type: website

website:
  title: "ISSS608-VAA"
  navbar:
    navbar:
    left:
      - text: "Hands-on Exercise"
        menu: 
          - text: "A Layered Grammar of Graphics: ggplot2 methods" 
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
      - text: "In-class Exercise"
        menu: 
        - text: "In-class Exercise 1"
      - text: "Take-home Exercise"
        menu:
          - text: "Take-home Exercise 1"
            href: "Take-home_Ex/Take-home_Ex01/Takehome_Ex01.html"
          - text: "Take Home Exercise 2"
            href: "Take-home_Ex/Take-home_Ex02/Take-home_Ex02.html"
          - text: "Take Home Exercise 3"
            href: "Take-home_Ex/Take-home_Ex03/Take-home_Ex03.html"
      
    right:
      - href: index.qmd
        text: "Home"
      - href: https://www.linkedin.com/in/erica-chan-6565b9218/
        icon: linkedin
      - href: https://github.com/clyerica/ISSS608-VAA
        icon: github


format:
  html:
    theme:
      - flatly
      - brand
    css: styles.css
    toc: true

editor: visual

