project:
  type: website

website:
  title: "ISSS608-VAA"
  navbar:
    navbar:
    left:
      - text: "Hands-on Exercise"
        menu: 
          - text: "A Layered Grammar of Graphics: ggplot2 methods" 
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
          - text: "Beyond ggplot2 Fundamentals"
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
          - text: "Programming Interactive Data Visualisation with R"
            href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03a.html"
          - text: "Programming Animated Statistical Graphics with R"
            href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03b.html"
          - text: "Visualising Distribution"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04a.html"
          - text: "Visual Statistical Analysis"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04b.html"
          - text: "Visualising Uncertainty"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04c.html"
          - text: "Funnel Plots for Fair Comparisons"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04d.html"
          - text: "Creating Ternary Plot with R"
            href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05a.html"
          - text: "Visual Correlation Analysis"
            href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05b.html"
          - text: "Heatmap for Visualising and Analysing Multivariate Data"
            href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05c.html"
          - text: "Visual Multivariate Analysis with Parallel Coordinates Plot"
            href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05d.html"
          - text: "Treemap Visualisation with R"
            href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05e.html"
          - text: "Visualising and Analysing Time-oriented Data"
            href: "Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07.html"
      - text: "In-class Exercise"
        menu: 
        - text: "In-class Exercise 1"
          href: "https://public.tableau.com/app/profile/erica.chan7164/viz/In-class_Ex01_17686351329540/Dashboard1?publish=yes"
        - text: "In-class Exercise 2"
          href: "https://public.tableau.com/app/profile/erica.chan7164/viz/In-class_Ex02_17692388707030/Dashboard2"
        - text: "In-class Exercise 3"
          href: "https://public.tableau.com/app/profile/erica.chan7164/viz/In-class_Ex03_17698445903810/Dashboard2"
      - text: "Take-home Exercise"
        menu:
          - text: "Take-home Exercise 1"
            href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html"
          - text: "Take Home Exercise 2"
            href: "Take-home_Ex/Take-home_Ex02/Take-home_Ex02.html"
          - text: "Take Home Exercise 3"
            href: "Take-home_Ex/Take-home_Ex03/Take-home_Ex03.html"
      
    right:
      - href: index.qmd
        text: "Home"
      - href: https://www.linkedin.com/in/erica-chan-6565b9218/
        icon: linkedin
      - href: https://github.com/clyerica/ISSS608-VAA
        icon: github


format:
  html:
    theme:
      - flatly
      - brand
    css: styles.css
    toc: true

editor: visual

